on: push
name: Make and upload artifacts

jobs:
    build-and-upload:
        name: Setup environment & build application
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Install Nodejs
            uses: actions/setup-node@v3
            with:
                node-version: 18.6.0
                cache: 'yarn'
          - name: Install dependencies
            run: yarn

          - name: Build application
            run: yarn start make

          - name: Upload artifacts
            uses: actions/upload-artifact@v3
            with:
                name: drop-farmer-windows-64bit
                path: out/make/zip/win32/x64/*.zip
