name: 'Build and Release'

on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build (${{ matrix.os }} - ${{ matrix.arch }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
                arch: [x64]
        steps:
            - uses: actions/checkout@v3

            - name: Create environment file
              uses: ozaytsev86/create-env-file@v1
              with:
                  ENV_STORES_ENCRYPTION_KEY: ${{secrets.STORES_ENCRYPTION_KEY}}
                  ENV_SUPABASE_BACKEND_URL: ${{secrets.SUPABASE_BACKEND_URL}}
                  ENV_SUPABASE_BACKEND_ANON_KEY: ${{secrets.SUPABASE_BACKEND_ANON_KEY}}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.15.0
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Build application
              run: yarn run make --arch=${{ matrix.arch }}

            - name: Create release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
              with:
                  draft: true
                  files: |
                      out/**/*.deb
                      out/**/*.dmg
                      out/**/*Setup.exe
                      out/**/*.nupkg
                      out/**/*.rpm
                      out/**/*.zip
                      out/**/RELEASES
