on:
    # only activate on master branch commits
    push:
        branches:
          - 'master'
name: Build application and upload artifacts

jobs:
    build-squirrel-x64:
        name: Build application (Windows x64)
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Install Nodejs
            uses: actions/setup-node@v3
            with:
                node-version: 18.6.0
                cache: 'yarn'
          - name: Install dependencies
            run: yarn

          - name: Build application
            run: yarn run make

          - name: Upload build artifacts
            uses: actions/upload-artifact@v3
            with:
                name: drop-farmer-windows-x64
                path: |
                    out/make/squirrel.windows/x64/drop-farmer-*Setup.exe
                    out/make/zip/**/drop-farmer*.zip
    build-squirrel-x32:
        name: Build application (Windows x32)
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Install Nodejs
            uses: actions/setup-node@v3
            with:
                node-version: 18.6.0
                cache: 'yarn'
          - name: Install dependencies
            run: yarn

          - name: Build application
            run: yarn run make --arch=ia32

          - name: Upload build artifacts
            uses: actions/upload-artifact@v3
            with:
                name: drop-farmer-windows-x32
                path: |
                    out/make/squirrel.windows/ia32/drop-farmer-*Setup.exe
                    out/make/zip/**/drop-farmer*.zip
    build-debian-x64:
        name: Build application (Debian x64 ARM64)
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Install Nodejs
            uses: actions/setup-node@v3
            with:
                node-version: 18.6.0
                cache: 'yarn'
          - name: Install dependencies
            run: yarn

          - name: Build application
            run: yarn run make --arch=arm64

          - name: Upload build artifacts
            uses: actions/upload-artifact@v3
            with:
                name: drop-farmer-debian-x64
                path: |
                    out/make/deb/arm64/drop-farmer*.deb
                    out/make/zip/**/drop-farmer*.zip
