on:
    push:
        tags:
            - "*"

name: "Create artifacts and create release draft"
jobs:
    publish-squirrel-x64:
        name: Publish (Squirrel Windows x64)
        runs-on: windows-latest
        env:
            GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18.6.0
                cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Publish
              run: yarn run publish
    publish-debian-arm64:
        name: Publish (Debian ARM64)
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18.6.0
                cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Publish
              run: yarn run publish --arch=arm64