on:
    push:
        tags:
            - "*"

name: Publish a release draft
jobs:
    build-artifacts:
        name: Build artifacts
        uses: Soryyyn/drop-farmer/.github/workflows/build-and-upload.yml@beta
    publish-draft:
        name: Publish draft
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18.6.0
                cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Publish
              run: yarn run publish